### ISSUE TITLE
About Temperature

### ISSUE THREAD

**Issue by KN1GHT9** [Lihr747/CgtGAN#4]
Congratulations on having your work accepted by ACM MM 2023! 
I have a question about the temperature, in your appendix the temperature is analyzed experimentally, but the final temperature parameter settings for each dataset are not given, is it possible to provide the training temperature parameters for different datasets as a reference?

**Comment by Lihr747** [comment]
Hello. Here are the training temperature parameters for different datasets.
MSCOCO images <---> MSCOCO captions: T=100 
Flickr30k images <---> Flickr30k captions: T=125 
MSCOCO images <---> Flickr30k captions: T=125 
Flickr30k images <---> MSCOCO captions: T=125 
MSCOCO images <---> SS captions: T=100 
MSCOCO images <---> GCC captions: T=175

**Comment by hemanthsrisai963** [comment]
Please guide through the training process
after running python preprocess/coco/coco_train_images.py
`(ta) D:\pp>python preprocess/coco/coco_train_images.py
saving path:./data/coco/coco_ViT-L_14_train_images.pkl
4 captions loaded from json
Traceback (most recent call last):
  File "preprocess/coco/coco_train_images.py", line 65, in <module>
    exit(main(args.clip_model_type, args.coco_path))
  File "preprocess/coco/coco_train_images.py", line 30, in main
    img_ids.add(d["image_id"])
TypeError: string indices must be integers`
this error what is the problem here

**Comment by hemanthsrisai963** [comment]
@Lihr747 
![error](https://github.com/Lihr747/CgtGAN/assets/82597780/809d7770-f76b-4e1d-be59-6991dfc9f055)
and also the annotations json files are not clear how should I process Please help me
